{% set name = "pymatgen-analysis-defects" %}
{% set version = "2025.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 563b9a07a8a9c05ddd42647d24dfb096f1d5956d1577d00453da418e623a3639

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioningit
  run:
    - python >={{ python_min }}
    - pymatgen >=2024.10.22
    - scikit-image >=0.19.3
    - numpy
    - mp-pyrho >=0.4.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymatgen.analysis.defects
    - pymatgen.analysis.defects.core

about:
  home: https://github.com/materialsproject/pymatgen-analysis-defects
  # See https://github.com/materialsproject/pymatgen-analysis-defects/issues/60
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: Defect analysis modules for pymatgen
  doc_url: https://materialsproject.github.io/pymatgen-analysis-defects/
  dev_url: https://github.com/materialsproject/pymatgen-analysis-defects

extra:
  recipe-maintainers:
    - njzjz
