{% set name = "pymatgen-analysis-defects" %}
{% set version = "2023.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 580832ee21a5c582ca84b066280da64214939dcb72c11418c6f4d9ca069a4664

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - versioningit
  run:
    - python >=3.8
    - pymatgen >=2022.10.22
    - scikit-image >=0.19.3

test:
  imports:
    - pymatgen.analysis.defects

about:
  home: https://github.com/materialsproject/pymatgen-analysis-defects
  # See https://github.com/materialsproject/pymatgen-analysis-defects/issues/60
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: Defect analysis modules for pymatgen
  doc_url: https://materialsproject.github.io/pymatgen-analysis-defects/
  dev_url: https://github.com/materialsproject/pymatgen-analysis-defects

extra:
  recipe-maintainers:
    - njzjz
